name: C/C++ CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: make lr1
        run: |
          echo "--- build ---"
          make build_lr1
          echo "--- run ---"

      - name: run lr1
        run: |
          echo "--- start ---"
          ./src/labs/n1/lab1.exe
          echo "--- finish ---"

      - name: make clean
        run: make clean
      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: src/data/raw/

  create_graph:
    runs-on: ubuntu-latest
    steps:
      - name: download python packages
        run: pip install matplotlib numpy

      - uses: actions/download-artifact@v4
        with:
          name: build-output
          path: src/data/raw/
      - run: python3 src/utils/create_graph.py

      - uses: actions/upload-artifact@v4
        with:
          name: graphs
          path: src/data/
