name: Graph Creating

on:
  workflow_dispatch:
    inputs:
      env:
        LAB_WORK_NUMBER: "Какая лабораторная(lr1, lr2)"
        required: true
        default: "n"
        type: choice
        options:
          - lr1
          - lr2
          - n

env:
  ARTIFACT_PATH: src/data/

jobs:
  make_lr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: make and run lr
        run: |
          echo "--- start ---"
          make ${{ env.LAB_WORK_NUMBER }}
          echo "--- finish ---"
          date +"%Y-%m-%d %H:%M:%S" > ${{ env.ARTIFACT_PATH }}data.md

      - uses: actions/upload-artifact@v5
        with:
          name: make-output
          path: ${{ env.ARTIFACT_PATH }}

  create_graph:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v5

      - name: download python packages
        run: pip install matplotlib

      - uses: actions/download-artifact@v5
        with:
          name: make-output
          path: ${{ env.ARTIFACT_PATH }}
      - run: |
          python3 src/utils/create.py
          date +"%Y-%m-%d %H:%M:%S" > ${{ env.ARTIFACT_PATH }}raw/data.md

      - uses: actions/upload-artifact@v5
        with:
          name: created_graphs
          path: ${{ env.ARTIFACT_PATH }}/graphs
